project:
  type: book
  output-dir: docs

extensions: [quarto-ext/panel]

lang: es  # <- idioma en espa침ol

book:
  title: "Alerta 1. Caracterizaci칩n de estudiantes"
  subtitle: "Encuesta de caracterizaci칩n de estudiantes de primer ingreso - 2025-1"
  author: "Direcci칩n de Anal칤tica Acad칠mica"
  date: "2025-05-05"
  reader-mode: true
  cover-image: "images/cover.png"  # Ruta a tu imagen de portada
  cover-image-alt: "Portada del libro Alerta 1"
  
  # Configuraci칩n de la barra lateral con 칤conos
  sidebar:
    tools:
      - icon: github
        href: https://github.com/udesanalitica/Alerta1_Cx_2025-1
        text: "Repositorio GitHub"
      - icon: printer
        href: "javascript:window.print()"
        text: "Imprimir"
    style: "docked"
    search: true
  
  # Configuraci칩n del pie de p치gina
  page-footer:
    left: |
      **Alerta 1. Caracterizaci칩n de estudiantes** fue creado por la 
      Direcci칩n de Anal칤tica Acad칠mica \Universidad de Santander.
    right: |
      Este libro fue construido con <a href="https://quarto.org/">Quarto</a>.
    center: |
      <a href="https://github.com/udesanalitica/Alerta1_Cx_2025-1" target="_blank" aria-label="GitHub">
        <i class="bi bi-github"></i>
      </a>
      <a href="#" aria-label="Compartir" style="margin-left: 10px;">
        <i class="bi bi-share"></i>
      </a>
      <a href="javascript:window.print()" aria-label="Imprimir" style="margin-left: 10px;">
        <i class="bi bi-printer"></i>
      </a>
  
  chapters:
    - index.qmd
    - intro.qmd
    - Seccion0.qmd
    - Seccion1.qmd
    - Seccion2.qmd
    - Seccion3.qmd
    - Seccion4.qmd
    - Conclusiones.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: 
      - cosmo
      - brand
    toc: true
    toc-depth: 3
    number-sections: true
    linkcolor: "#046A38"
    fontsize: 1em
    css: style.css
    fig-cap-location: top
    reference-location: margin
    cite-method: citeproc
    biblio-style: apa
    
    # Configuraci칩n del repositorio para 칤conos autom치ticos
    repo-url: https://github.com/udesanalitica/Alerta1_Cx_2025-1
    repo-actions: [edit, issue, source]
    repo-subdir: ""
    
    # Incluir Bootstrap Icons para los 칤conos
    include-in-header: header.html
      
    crossref:
      chapters: true
      title-delim: "."
      fig-prefix: "Figura"
      tbl-prefix: "Tabla"
    page-layout: full  # 游댲 Asegura que plotly use todo el ancho sin desbordes

editor: visual
